[server]
headless = true
port = 8501
server.address = "0.0.0.0"
enableCORS = false 
enableXsrfProtection = false
maxUploadSize = 200

[theme]
base = "dark"
primaryColor = "#F63366"
backgroundColor = "#0E1117"  # A dark gray instead of white
secondaryBackgroundColor = "#1A1D23"  # A slightly lighter dark shade
textColor = "#FAFAFA"  # White text for contrast
font = "monospace"  # You can use "serif" or "monospace"

